### ISSUE TITLE
BeamNG scenario never start

### ISSUE THREAD

**Issue by RoboticistAbdulrahman** [ChristianBirchler/sdc-scissor#62]
1. i activate the virtual environment of sdc-scissor project 
2. i run the sample test  `poetry run sdc-scissor -c sample_configs/label-tests.yml `
3. BeamNG.Tech start, and call the scenario, but the scenario never start. 

![image](https://user-images.githubusercontent.com/94268081/178990973-583eebbc-5e0d-491d-8dbd-06021b671f11.png)
[terminal_output](https://github.com/ChristianBirchler/sdc-scissor/files/9112088/sdc.bug.txt)

# Resulting and expected behavior
some tests should be generated

# System information
* OS: windows 11
* CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
* GPU: RTX 3060

* Software:  version v2.2 of SDC-Scissor

**Comment by ChristianBirchler** [comment]
Thanks @RoboticistAbdulrahman for the report. What does the BeamNG console output?

**Comment by RoboticistAbdulrahman** [comment]
001.541|I|Paths|User path: C:\Users\User\AppData\Local\BeamNG.drive\0.24\
005.253|I|GELua.print|*************LightRayPostFX 2 set
005.260|I|GELua.print|********PostFXSSAOGeneralEnabled 2 set
008.088|W|GELua.core_levels.|info.json missing: /levels/grid_small_pure/info.json
008.090|E|GELua.core_levels.|No entry point for level found: /levels/grid_small_pure. Ignoring level.
008.090|W|GELua.core_levels.|info.json missing: /levels/GridMap/info.json
008.092|E|GELua.core_levels.|No entry point for level found: /levels/GridMap. Ignoring level.
008.095|W|GELua.core_levels.|info.json missing: /levels/tig/info.json
008.096|E|GELua.core_levels.|No entry point for level found: /levels/tig. Ignoring level.
010.401|I|GELua.util_researchGE.ResearchGE|Accepted new client: 127.0.0.1/64256
015.861|I|GELua.util_researchGE.ResearchGE|Loading scenario: /levels/tig/scenarios/example.json
016.011|I|GELua.util_researchGE.ResearchGE|Scenario found...
016.748|I|GELua.levelLoading|*** loading level: levels/tig/info.json
016.749|I|GELua.levelLoading|*** Loading init took: 0.163 s
017.020|I|GELua.levelLoading|*** Loaded datablocks in 0.271 s
017.022|I|GELua.levelLoading|*** Loaded materials in 0.003 s
017.023|E|GELua.levelLoading|Could not find level: levels/tig/info.json
322.872|W|GELua.core_levels.|info.json missing: /levels/grid_small_pure/info.json
322.874|E|GELua.core_levels.|No entry point for level found: /levels/grid_small_pure. Ignoring level.
322.877|W|GELua.core_levels.|info.json missing: /levels/GridMap/info.json
322.878|E|GELua.core_levels.|No entry point for level found: /levels/GridMap. Ignoring level.
322.880|W|GELua.core_levels.|info.json missing: /levels/tig/info.json
322.881|E|GELua.core_levels.|No entry point for level found: /levels/tig. Ignoring level.
322.918|E|GELua.|No game["freeCamera"] object found
322.932|E|GELua.|No game["freeCamera"] object found
322.946|E|GELua.|No game["freeCamera"] object found
322.957|E|GELua.|No game["freeCamera"] object found
322.968|E|GELua.|No game["freeCamera"] object found
322.992|E|GELua.|No game["freeCamera"] object found
323.001|E|GELua.|No game["freeCamera"] object found
323.009|E|GELua.|No game["freeCamera"] object found
323.018|E|GELua.|No game["freeCamera"] object found
323.026|E|GELua.|No game["freeCamera"] object found
323.036|E|GELua.|No game["freeCamera"] object found
323.043|E|GELua.|No game["freeCamera"] object found
323.054|E|GELua.|No game["freeCamera"] object found
323.062|E|GELua.|No game["freeCamera"] object found
323.069|E|GELua.|No game["freeCamera"] object found
323.077|E|GELua.|No game["freeCamera"] object found
323.085|E|GELua.|No game["freeCamera"] object found
323.093|E|GELua.|No game["freeCamera"] object found
323.104|E|GELua.|No game["freeCamera"] object found
323.123|E|GELua.|No game["freeCamera"] object found
323.501|E|GELua.|No game["freeCamera"] object found

**Comment by ChristianBirchler** [comment]
Hi @RoboticistAbdulrahman, thanks for sharing the logs. It seems it does not find the level. Did you copy-paste the level from the repository (https://github.com/ChristianBirchler/sdc-scissor/tree/main/levels_template/tig) to BeamNG's user directory?

SDC-Scissor uses a very simple level you need to add to BeamNG. I have to check if I missed documenting this. This might cause the issue due to the lack of documentation.

**Comment by RoboticistAbdulrahman** [comment]
Yeaaah, it finally works now, Thanks @ChristianBirchler

**Comment by ChristianBirchler** [comment]
It is documented: https://sdc-scissor.readthedocs.io/en/latest/software_guidebook/deployment.html#beamng
